<?php

/**
 * @var Index $block
 */

use Hiberus\Rebordinos\Block\Index;

$exams = $block->getExams();
$passnote= $block->getPassNote();
$size= $block->getSize();
$i=0;
?>

<h2 class="title"><?= __('Exams') ?></h2>

<button id="open_details" ><?= __('Show/Hide data') ?></button>

<div id="details">


    <?php foreach ($exams as $item) {
        if ($i++ == $size) break;?>
        <ul>
            <li><?= __('First name') ?>: <?= $item->getFirstname() ?></li>
            <li><?= __('Last name') ?>: <?= $item->getLastname() ?></li>

            <?php if($item->getMark() < $passnote){
                $class="exam-fail";
            }else{
                $class="exam-pass";
            } ?>
            <li class="<?=$class?>"><?= __('Mark') ?>: <?=$item->getMark()?></li>
        </ul>

    <?php } ?>

</div>
<p><?= __('Total number of %1 students', [$size]) ?></p>
<p><?= __('The average mark: %1', [$block->getAverageMark()]) ?></p>

<script>
    require(['jquery', 'myscript'], function($, myscript) {
        myscript('#open_details','#details');
    });
</script>
