<?php

/**
 * @var \Hiberus\Rebordinos\Block\Index $block
 */
$exams = $block->getExams();
var_dump($exams);die();
?>

<h2 class="title">Exams</h2>
<?php foreach ($exams as $item) {?>
    <ul>
        <li>Name: <?= $item->getFirstname() ?></li>
        <li>Lastname: <?= $item->getLastname() ?></li>
        <li>Mark: <?= $item->getMark() ?></li>
    </ul>
<?php } ?>
<p>Total number of students:.</p>


