<?php

/**
 * @var Index $block
 */

use Hiberus\Rebordinos\Block\Index;

$exams = $block->getExams();

?>

<h2 class="title">Exams</h2>
<?php foreach ($exams as $item) {?>
    <ul>
        <li>First name: <?= $item->getFirstname() ?></li>
        <li>Last name: <?= $item->getLastname() ?></li>

        <?php if($item->getMark() < 5){
            $class="exam-fail";
        }else{
            $class="exam-pass";
        } ?>
        <li class="<?=$class?>">Mark: <?=$item->getMark()?></li>


    </ul>
<?php } ?>

<p><?= __('Total number of %1 students', [sizeof($exams)]) ?></p>
<p><?= __('The average mark: %1', [$block->getAverageMark()]) ?></p>

